### ISSUE TITLE
Halp mi

### ISSUE THREAD

**Issue by JohnSmith268** [mattn/go-shellwords#10]
When i do 'go get github.com/mattn/go-shellwords' on my vps which is Debian Jessie 8 32 bit i get the error  eerr.Stderr undefined (type *exec.ExitError has no field or method Stderr)

**Comment by mattn** [comment]
What version of go do you use?

**Comment by JohnSmith268** [comment]
I use go1.5

**Comment by mattn** [comment]
Could you please this [PR](https://github.com/mattn/go-shellwords/pull/11)?
