### ISSUE TITLE
Use custom environment instead of os.Getenv?

### ISSUE THREAD

**Issue by itayd** [mattn/go-shellwords#18]
Hi, i suggest the ability to replace the `os.Getenv` function with a generic function - to be more specific adding another field to parser (https://github.com/mattn/go-shellwords/blob/master/shellwords.go#L34):

```
type Parser struct {
	ParseEnv      bool
        Getenv        func(string) string
	ParseBacktick bool
	Position      int
}
```

if it is `nil`, os.Getenv is used (this is for backward compatibility). If it weren't for backward compatibility, I would suggest it replaces the ParseEnv variable entirely.

Would be happy to send out a PR if this makes sense.

**Comment by itayd** [comment]
ping?

**Comment by mattn** [comment]
Could you please send me PR?

**Comment by mattn** [comment]
closed by https://github.com/mattn/go-shellwords/pull/19
