### ISSUE TITLE
Support smart quotes

### ISSUE THREAD

**Issue by Kegsay** [mattn/go-shellwords#2]
I appreciate this project is old and may not be maintained anymore, but before forking it I thought I'd file my particular feature request in the event that it is still maintained.

It would be great if the `Parser` had an option to `ParseSmartQuotes`, which would:
 - Treat `“` and `”` as `"`.
 - Treat `‘` and `’` as `'`.

That's it. Thanks!

**Comment by mattn** [comment]
Sorry, I don't like this because go-shellwords parse the string that it is possible to run as shell commands. Your smart quotes is not possibly commands.

**Comment by TomOnTime** [comment]
Suggestion: make those substitutions before calling go-shellwords. Then you don't need to fork anything.
