### ISSUE TITLE
Update captures `|`

### ISSUE THREAD

**Issue by relvacode** [mattn/go-shellwords#4]
My code uses `|` pipe character, the @753a2322a99f87c0eff284980e77f53041555bc6 commit now captures this character and discards the remaining line.

Could you add an option to disable this? And the other characters now being captured by the library.

**Comment by mattn** [comment]
Sorry about breaking compatibility. This should be required change. Try to look this test.

https://github.com/mattn/go-shellwords/blob/master/shellwords_test.go#L154-L180

Using Parser.Parse, you can see Parser#Position to figure out the text remainings. So please skip `|` and try to parse the next.
