### ISSUE TITLE
Some unexpected quote handling behavior when ParseEnv is true

### ISSUE THREAD

**Issue by wtetsu** [mattn/go-shellwords#48]
Hello, thank you for this great library.
I've been using go-shellwords in my applications and it greatly helps me.

---

I've noticed go-shellwords's quote handling is different from general shells when `ParseEnv` is true.

Is it possible to change that, or is this intentional behavior?

### shell

```
$ cat a.sh
echo 0:$1
echo 1:$2
echo 2:$3

$ bash a.sh a '' c
0:a
1:
2:c
```

### go-shellwords

```go
parser := shellwords.Parser{ParseEnv: true}
result, _ := parser.Parse("a '' c")
for i, v := range result {
  fmt.Printf("%d:%s\n", i, v)
}
// Result:
// 0:a
// 1:c
```

----

| Input     | go-shellwords(2c8720d) | Expected     |
| --------- | ---------------------- | ------------ |
| a '' c    | 0:a, 1:c               | 0:a, 1:, 2:c |
| 'A B C' c | 0:A, 1:B, 2:C, 3:c     | 0:A B C, 1:c |
| 'A "B' c  | (Error)                | 0:A "B, 1:c  |
| '${TEMP}' | 0:/tmp                 | 0:${TEMP}    |

**Comment by eikenb** [comment]
Recently ran into this issue upgrading from 1.0.5 to 1.0.10 when parsing subshell commands like `"sh -c 'echo foo'"`. In 1.0.5 and 1.0.10 w/o ParseEnv set returns `[]string{"sh", "-c", "echo hi"}`. 1.0.10 with ParseEnv set returns `[]string{"sh", "-c", "echo", "hi"}`.

Tracked it down to release v1.0.8, commit https://github.com/mattn/go-shellwords/commit/0ee2d7a36f0d4980dcf451b61d95d8be69866f56

Simple test to reproduce it...

```sh
func TestSubShell(t *testing.T) {
	myParser := &Parser{
		ParseEnv:      true,
		ParseBacktick: true,
	}
	args, err := myParser.Parse(`sh -c 'echo foo'`)
	if err != nil {
		t.Fatalf("err should be nil: %v", err)
	}
	expected := []string{"sh", "-c", "echo foo"}
	argErr := fmt.Sprintf("bad arg parsing:\nexpected: %#v\nactual  : %#v\n",
		expected, args)
	if len(args) != 3 {
		t.Fatal(argErr)
	}
	if args[0] != expected[0] || args[1] != expected[1] || args[2] != expected[2
] {
		t.Fatal(argErr)
	}
}
```
