### ISSUE TITLE
parsing empty strings

### ISSUE THREAD

**Issue by immesys** [mattn/go-shellwords#5]
I would expect that 
```
Parse(`foo "" bar ''`)
```
would give ["foo", "", "bar", ""] with the empty strings appearing as results, but this is not the case, you would only get ["foo","bar"]. Is this intended behavior?

**Comment by marckhouzam** [comment]
This still does not work for me.

```
package main

import (
	"fmt"

	shellwords "github.com/mattn/go-shellwords"
)

func main() {
	args, _ := shellwords.Parse(`foo "" bar ''`)
	fmt.Printf("num args %d, args %v", len(args), args)
}
```
gives
```
num args 2, args [foo bar]
```
You can try it directly: https://play.golang.org/p/afqKID3VJ7I
