### ISSUE TITLE
escape from & when parsing shellwords

### ISSUE THREAD

**Issue by bbx-winner** [mattn/go-shellwords#51]
## Bad Case

I tried to parse `curl http://httpbin.org/get?a=1&b=2` to shell word list as the following code

```golang
package main

import (
	"fmt"
	"log"

	"github.com/mattn/go-shellwords"
)

func main() {
	sw, err := shellwords.Parse("curl http://httpbin.org/get?a=1&b=2")
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(sw)
}
```

- expect: `[curl http://httpbin.org/get?a=1&b=2]`
- actal: `[curl http://httpbin.org/get?a=1]`

## version
go: 1.16.5
go-shellwords: v1.0.12

**Comment by mattn** [comment]
it works as intended. please quote the argument.
