### ISSUE TITLE
Create a licence file

### ISSUE THREAD

**Issue by mkumatag** [mattn/go-shellwords#6]
Docker is using this as vendor package. In docker we can check for checking copyright for all the vendor packages and expects any files in `.*LICENSE.*' '.*COPYRIGHT.*'  '.*COPYING.*'` pattern, currently while validating this package it is printing the warning message.

Please create explicit licence file to avoid any warnings while validation, so create a LICENCE file in parent directory with the MIT licence referred in the README file.

**Comment by mkumatag** [comment]
Can I expect any version bump with this fix?

**Comment by mattn** [comment]
okay, will do soon

**Comment by mkumatag** [comment]
Thanks @mattn
